### ISSUE TITLE
How to change initial volume level ?

### ISSUE THREAD

**Issue by fpp-gh** [marco79cgn/radio-paradise#6]
Hi Marco,
I'm using your "proof of concept" which runs really well in a Chrome app-window (and I hope it stays that way :-).

My only gripe is that the volume is set at 1 (100%) by default, which is very loud on my stereo, and I need to turn it down each time (and sometimes I forget :-).

I've tried to change the default self._volume in the howler-core.js init to 0.5, but clearly it's not enough.
I also looked into player.js, but unfortunately I'm hopeless with JS (Python guy myself :-) and didn't see any other easy changes to try out.

Any hints about this (probably trivial) modification welcome, and thanks for the player !
TIA,
fp

**Comment by marco79cgn** [comment]
Hi,
always nice to read that people still use it, thanks.

This is an easy one. Just put the following code in line 371 in player.js:
`player.volume(0.5);`
You can even overwrite the existing "//player.play()" (and remove the double slashes) since autoplaying when loading a site is not supported in most browsers anymore due to security reasons.

Cheers,
Marco

**Comment by fpp-gh** [comment]
Thanks again for the very fast response Marco !
I just added the line, works just great !
Best,
fp
